global: 
  storageClass: ""

postgresql:
  image: "postgres:15"
  database: "vault"
  user: "vault"
  password: "vaultpassword"
  storage:
    size: "10Gi"
  service:
    name: postgres
    type: ClusterIP
    port: 5432  # Ensure port is correctly set

vault:
  image: "hashicorp/vault:latest"
  service: 
    name: vault
    type: ClusterIP
    port: 8200  # Vault should have its own port for API access
  ingress:
    enabled: false
    host: "vault.local"  # Fixed missing quote
